INSERT INTO PUBLIC.AUTHORITY
  SELECT
    *
  FROM (
         SELECT 0, 'ROLE_USER'
         UNION
         SELECT 1, 'ROLE_ADMIN'
         UNION
         SELECT 2, 'ROLE_AGENT'
         UNION
         SELECT 3, 'ROLE_MANAGER'
       ) x WHERE NOT exists(SELECT * FROM AUTHORITY);
